<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2011 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2011 Sun Microsystems, Inc.
 */

//~ Template for detail.php
// variables:
//  $todo - TODO to be displayed
//  $tooLate - if the task should have been done already

/* @var $todo Todo */
?>

<h1>    
    <?php echo Utils::escape($todo->getNombre()); ?>
</h1>

<table class="detail">    
    <tr>
        <th>Creada</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($todo->getCreatedOn())); ?></td>
    </tr>
    <tr>
        <th>Género</th>
        <td>
            <?php echo Utils::escape($todo->getGenero()); ?>            
        </td>
    </tr>
    <tr>
        <th>Edad</th>
        <td>
            <?php echo Utils::escape($todo->getEdad()); ?>            
        </td>
    </tr>
    <tr>
        <th>Región</th>
        <td><?php echo Utils::escape($todo->getRegion()); ?></td>
    </tr>
    <tr>
        <th>Nacionalidad</th>
        <td><?php echo Utils::escape($todo->getNacionalidad()); ?></td>
    </tr>
    <tr>
        <th>Residencia</th>
        <td><?php echo Utils::escape($todo->getResidencia()); ?></td>
    </tr>
    <tr>
        <th>Profesión</th>
        <td><?php echo Utils::escape($todo->getProfesion()); ?></td>
    </tr>
    <tr>
        <th>Correo Electrónico</th>
        <td><?php echo Utils::escape($todo->getEmail()); ?></td>
    </tr>
    <tr>
        <th>Estado Civil</th>
        <td><?php echo Utils::escape($todo->getEdoCivil()); ?></td>
    </tr>
    <tr>
        <th>Número de Hijos</th>
        <td><?php echo Utils::escape($todo->getNumHijos()); ?></td>
    </tr>
    <tr>
        <th>Comentario</th>
        <td><?php echo Utils::escape($todo->getComment()); ?></td>
    </tr>
    <tr>
        <th>Resultado</th>
        <td><?php echo Utils::escape($todo->getResultadoStr()); ?></td>
    </tr>
    <tr>
        <th>Resiliencia</th>
        <td><?php echo Utils::escape($todo->getResiliencia()); ?></td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>    
</table>

<p>
    <li><span><a href="<?php echo Utils::createLink('home'); ?>">Inicio</a></span></li>
</p>

<div id="delete-dialog" title="Delete this TODO?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This TODO will be deleted. Are you sure?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
